[package]
name = "yoga"
description = "Rust bindings for Facebook's Yoga, a Flexbox layout engine"
license = "MIT"
repository = "https://github.com/bschwind/yoga-rs"
version = "0.2.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.32.0"
gcc = "0.3.54"

[dependencies]
ordered-float = "0.5.0"
